\getenv api_password API_DB_PASSWORD
CREATE ROLE insta_api LOGIN PASSWORD :'api_password';
GRANT CONNECT ON DATABASE insta TO insta_api;
GRANT USAGE ON SCHEMA public TO insta_api;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO insta_api;
